a4s/urls.py
# a4s/urls.py

from django.urls import path

from .views import (
    HomeView,
    AskQuestionView,
    QuestionDetailView,
    CreateAnswerView,
    UpdateAnswerAcceptanceView,
    DailyQuestionList,
    TodaysQuestionList,
    QuestionListView,
)


app_name = 'a4s'
urlpatterns = [
    path('',
         HomeView.as_view(),
         name='home'
         ),
    path('ask/',
         AskQuestionView.as_view(),
         name='ask_question'
         ),
    path('question/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         QuestionDetailView.as_view(),
         name='question_detail'
         ),
    path('question/<int:pk>/answer/',
         CreateAnswerView.as_view(),
         name='create_answer'
         ),
    path('answer/<int:pk>/accept/',
         UpdateAnswerAcceptanceView.as_view(),
         name='update_answer_acceptance'
         ),
    path('questions/<int:year>/<int:month>/<int:day>/',
         DailyQuestionList.as_view(),
         name='daily_question_list'
         ),
    path('questions/today/',
         TodaysQuestionList.as_view(),
         name='daily_question_list'
         ),
    path('questions/',
         QuestionListView.as_view(),
         name='question_list'
         ),
]

ask4solution/urls.py
# ask4solution/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('a4s.urls')),
]

a4s/models.py
# a4s/models.py

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


class Question(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    asker = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=250, unique_for_date='created')

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("a4s:question_detail", kwargs={"pk": self.pk})

    # for generating seo freindly url by using slug
    def get_absolute_url(self):
        return reverse(
            'a4s:question_detail',
            args=[
                self.created.year,
                self.created.month,
                self.created.day,
                self.slug
            ]
        )

    def can_accept_answers(self, user):
        return user == self.asker


class Answer(models.Model):
    description = models.TextField()
    solver = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

a4s/forms.py
# a4s/forms.py

from django import forms
from django.contrib.auth import get_user_model

from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    asker = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,  # ignore any values provided by data (from a request)
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 7, 'cols': 40}
        )
    )

    class Meta:
        model = Question
        fields = ['title', 'description', 'asker', ]


class AnswerForm(forms.ModelForm):
    solver = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,  # ignore any values provided by data (from a request)
    )
    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Question.objects.all(),
        disabled=True,  # ignore any values provided by data (from a request)
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'cols': 40}
        )
    )

    class Meta:
        model = Answer
        fields = ['description', 'solver', 'question']


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    class Meta:
        model = Answer
        fields = ['accepted', ]

a4s/views.py
# a4s/views.py

from django.views.generic import (
    TemplateView,
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DayArchiveView,
    RedirectView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, HttpResponseBadRequest
from django.utils.text import slugify
from django.urls.base import reverse
from django.utils import timezone

from .models import Question, Answer
from .forms import QuestionForm, AnswerForm, AnswerAcceptanceForm


class HomeView(TemplateView):
    template_name = 'a4s/home.html'


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'a4s/ask_question.html'

    # initial values provided to the form
    def get_initial(self):
        return {
            'asker': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            form.instance.slug = slugify(form.cleaned_data['title'])
            # save and redirect
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'a4s/question_detail.html'

    ACCEPT_FORM = AnswerAcceptanceForm(initial={'accepted': True})
    REJECT_FORM = AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'answer_form': AnswerForm(initial={
                'solver': self.request.user.id,
                'question': self.object.id,
            })
        })
        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.ACCEPT_FORM,
                'reject_form': self.REJECT_FORM,
            })
        return ctx


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = 'a4s/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'solver': self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            # save and redirect as usual.
            return super().form_valid(form)
        elif action == 'PREVIEW':
            ctx = self.get_context_data(
                preview=form.cleaned_data['description'])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(
            redirect_to=self.object.question.get_absolute_url())


class DailyQuestionList(DayArchiveView):
    template_name = 'a4s/question_archive_day.html'
    queryset = Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            'a4s:daily_question_list',
            kwargs={
                'day': today.day,
                'month': today.month,
                'year': today.year,
            }
        )


class QuestionListView(ListView):
    model = Question
    template_name = 'a4s:question_list'
    paginate_by = 3

a4s/templates/a4s/sub/display_question.html
<!-- a4s/templates/a4s/sub/display_question.html -->

{% load markdownify %}
<div class="card" >
  <div class="card-header">
    <h5>Question</h5>
  </div>
  <div class="card-body">
    <span class="lead">{{ question.title }}</span><br/>
    <kbd class="text-muted small bg-light">
      Asked by <strong>{{ question.asker }}</strong> | {{ question.created }}
    </kbd><hr />
    <p>{{ question.description|markdownify }}</p>
  </div >
</div> 

a4s/templates/a4s/sub/list_answers.html
<!-- a4s/templates/a4s/sub/list_answers.html -->

{% load markdownify %}

<div class="card" >
  <div class="card-header">
    <h5>Answers</h5>
  </div>
  <div class="card-body">
    <ul class="list-unstyled" >
      {% for answer in question.answer_set.all %}
        <li class="row">
          <div class="col-sm-2 col-md-1 text-center" >
            {% if answer.accepted %}
              <span class="badge badge-pill badge-success">Accepted</span >
            {% endif %}
            {% if answer.accepted and reject_form %}
              <form method="post"
                    action="{% url "a4s:update_answer_acceptance" pk=answer.id %}">
                    {% csrf_token %}
                    {{ reject_form }}
                    <button type="submit" class="btn btn-link" title="Reject answer">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        Reject
                    </button >
              </form >
            {% elif accept_form %}
              <form method="post"
                    action="{% url "a4s:update_answer_acceptance" pk=answer.id %}" >
                    {% csrf_token %}
                    {{ accept_form }}
                    <button type="submit" class="btn btn-link" title="Accept answer">
                        <i class="fa fa-check-circle" aria-hidden="true"></i >
                        Accept
                    </button >
              </form >
            {% endif %}
          </div >
          <div class="col-sm-10 col-md-11" >
            <div class="body" >{{ answer.description|markdownify }}</div >
            <div class="" >
              <kbd class="text-muted bg-light small">
                Answered by <strong>{{ answer.solver }}</strong> | {{ answer.created }}
              </kbd>
            </div >
          </div >
        </li >
        {% if not forloop.last %}<hr />{% endif %}
      {% empty %}
        <li class="answer" >No answers yet!</li >
      {% endfor %}
    </ul>
  </div>
</div > 

a4s/templates/a4s/sub/post_answer.html
{% load crispy_forms_tags %}

<div class="card" >
  <div class="card-header">
    <h5>Post Your Answer</h5>
  </div>
  <div class="card-body">
        <form method="post" action="{% url "a4s:create_answer" pk=question.id %}">
                {{ answer_form | crispy }}
                {% csrf_token %}
                <button class="btn btn-primary" type="submit" name="action" value="PREVIEW">Preview
                </button>
                <button class="btn btn-primary" type="submit" name="action" value="SAVE">Answer
                </button>
        </form>
  </div >
</div > 