a4s/urls.py
# a4s/urls.py

from django.urls import path

from .views import (
    HomeView,
    AskQuestionView,
    QuestionDetailView,
    CreateAnswerView,
    UpdateAnswerAcceptanceView,
    DailyQuestionList,
    TodaysQuestionList,
    QuestionListView,
)


app_name = 'a4s'
urlpatterns = [
    path('',
         HomeView.as_view(),
         name='home'
         ),
    path('ask/',
         AskQuestionView.as_view(),
         name='ask_question'
         ),
    path('question/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         QuestionDetailView.as_view(),
         name='question_detail'
         ),
    path('question/<int:pk>/answer/',
         CreateAnswerView.as_view(),
         name='create_answer'
         ),
    path('answer/<int:pk>/accept/',
         UpdateAnswerAcceptanceView.as_view(),
         name='update_answer_acceptance'
         ),
    path('questions/<int:year>/<int:month>/<int:day>/',
         DailyQuestionList.as_view(),
         name='daily_question_list'
         ),
    path('questions/today/',
         TodaysQuestionList.as_view(),
         name='daily_question_list'
         ),
    path('questions/',
         QuestionListView.as_view(),
         name='question_list'
         ),
]

ask4solution/urls.py
# ask4solution/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('a4s.urls')),
]

users/urls.py
# users/urls.py

from django.urls import path

from .views import SignupView

app_name = 'users'
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
]

templates/base.html
<!-- templates/base.html  -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'base.css' %}">

    <title>{% block title %}ask4solution{% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{% url 'a4s:home' %}"><code>&lt;ask4solution&gt;</code></a>
        <ul class="navbar-nav mx-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'a4s:ask_question' %}">Ask Question</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" 
                href="{% url 'a4s:daily_question_list' %}">Daily Questions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'a4s:question_list' %}">All Questions</a>
            </li>
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
                <a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">Sign Up</a>
            </form>
            {% endif %}
        </div>
    </nav>
    <div class="container mb-3">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>